const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const COLORS={P:'#50b9dc',A:'#f4b942',H:'#a78bfa',T:'#ff6b6b'}, NAMES={P:'Parcial',A:'Anular',H:'Híbrido',T:'Total'};
const MONTHS={Jan:'enero',Feb:'febrero',Mar:'marzo',Apr:'abril',May:'mayo',Jun:'junio',Jul:'julio',Aug:'agosto',Sep:'septiembre',Oct:'octubre',Nov:'noviembre',Dec:'diciembre'};
let data=null,index=0,timer=null;
function date(e){return e.year<=0?`${e.day} de ${MONTHS[e.month]} de ${1-e.year} a. C.`:`${e.day} de ${MONTHS[e.month]} de ${e.year}`}
function duration(v){if(!v)return'No aplica';let m=v.match(/(\d\d)m(\d\d)s/);return m?`${+m[1]} min ${+m[2]} s`:v}
async function load(n){if(!Number.isInteger(n)||n<0||n>180){showError('El número debe estar entre 0 y 180.');return}stop();$('#loading').hidden=false;$('#app').hidden=true;$('#error').hidden=true;try{let r=await fetch(`data/saros-${String(n).padStart(3,'0')}.json`);if(!r.ok)throw Error('No se pudo abrir esta familia de eclipses.');let j=await r.json();data=j;index=j.events.reduce((b,e,i)=>Math.abs(e.year-2026)<Math.abs(j.events[b].year-2026)?i:b,0);build();render()}catch(e){showError(e.message)}finally{$('#loading').hidden=true}}
function showError(t){$('#error').textContent=t;$('#error').hidden=false;$('#loading').hidden=true}
function build(){
 $('#app').hidden=false;$('#seriesNumber').textContent=`Saros ${data.number}`;$('#seriesDuration').textContent=`${data.durationYears.toFixed(2)} años`;$('#seriesSequence').textContent=data.sequence;$('#seriesNode').textContent=`${data.node} · ${data.movement}`;
 $('#timeline').innerHTML=data.events.map((e,i)=>`<button aria-label="Eclipse ${i+1}: ${date(e)}" data-i="${i}" style="--type:${COLORS[e.kind]}"></button>`).join('');
 $$('#timeline button').forEach(b=>b.onclick=()=>{stop();index=+b.dataset.i;render()});
 $('#legend').innerHTML=['P','A','H','T'].map(k=>{let n=data.events.filter(e=>e.kind===k).length;return n?`<span><i style="background:${COLORS[k]}"></i>${NAMES[k]} <b>${n}</b></span>`:''}).join('');
 $('#atlasWarning').hidden=data.atlasComplete;if(!data.atlasComplete)$('#atlasWarning').textContent=`La familia completa contiene ${data.totalEclipses} eclipses; el canon cartográfico de −1999 a +3000 ofrece ${data.events.length} mapas.`;
 drawClockBars();drawChart();
}
function render(){let e=data.events[index],c=COLORS[e.kind];$('#counter').textContent=`ECLIPSE ${index+1} DE ${data.events.length} · RELATIVO ${e.relativeNumber>=0?'+':''}${e.relativeNumber}`;$('#date').textContent=date(e);$('#typeBadge').textContent=NAMES[e.kind];$('#typeBadge').style.setProperty('--type',c);$('#mapImage').src=e.mapUrl;$('#mapImage').alt=`Mapa global del eclipse ${date(e)}`;$('#factType').textContent=NAMES[e.kind];$('#factMagnitude').textContent=e.magnitude.toFixed(4);$('#factGamma').textContent=e.gamma.toFixed(4);$('#factDuration').textContent=e.kind==='P'?'No aplica':duration(e.duration);$('#factWidth').textContent=e.width?`${e.width} km`:'—';$('#factLocation').textContent=`${e.latitude}, ${e.longitude}`;$('#gammaReading').innerHTML=`<b>|γ| = ${Math.abs(e.gamma).toFixed(3)}</b>. Es la distancia mínima aproximada entre el eje de la sombra y el centro terrestre, en radios ecuatoriales.`;$$('#timeline button').forEach((b,i)=>b.classList.toggle('active',i===index));
 let rule={T:'α☾ > α☉: la Luna se ve mayor y tapa todo el Sol.',A:'α☾ < α☉: la Luna se ve menor y queda un anillo.',H:'α☾ ≈ α☉: la curvatura terrestre cambia total ↔ anular.',P:'El eje de la umbra no corta la Tierra: solo llega la penumbra.'}[e.kind];$('#typeRule').textContent=`Eclipse seleccionado: ${NAMES[e.kind]}. ${rule}`;$('#typeRule').style.setProperty('--type',c);placeGamma(e.gamma);drawChart();}
function move(d){stop();index=Math.max(0,Math.min(data.events.length-1,index+d));render()}
function stop(){if(timer)clearInterval(timer);timer=null;$('#play').textContent='▶'}
$('#prev').onclick=()=>move(-1);$('#next').onclick=()=>move(1);$('#exeligmos').onclick=()=>move(3);$('#play').onclick=()=>{if(timer){stop();return}$('#play').textContent='Ⅱ';timer=setInterval(()=>{index=(index+1)%data.events.length;render()},850)};
$('#search').onsubmit=e=>{e.preventDefault();load(Number($('#number').value))};
$$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.toggle('active',x===b));$$('.lesson').forEach(x=>x.classList.toggle('active',x.id===b.dataset.tab))});
function drawClockBars(){let rows=[['Sinódico · 223 S',29.530588853*223,'#ef7d45'],['Draconítico · 242 D',27.212220817*242,'#63c9d0'],['Anomalístico · 239 A',27.55454988*239,'#a78bfa']],base=rows[0][1],min=6585.25,max=6585.60;$('#clockBars').innerHTML=rows.map(([n,v,c],i)=>`<div class="bar-row"><label>${n}</label><div class="bar"><i style="--color:${c};--width:${(v-min)/(max-min)*100}%"></i></div><b>${v.toFixed(4)} d</b><small>${i?'Diferencia: '+((v-base)*24).toFixed(2)+' h':'Referencia del Saros'}</small></div>`).join('')}
function placeGamma(g){let r=Math.min(Math.abs(g),1.45)/1.45*145,a=(g>=0?-38:142)*Math.PI/180,x=Math.cos(a)*r,y=Math.sin(a)*r,p=$('#gammaPoint'),v=$('#gammaVector');p.style.transform=`translate(${x}px,${y}px)`;v.style.width=`${r}px`;v.style.transform=`rotate(${a}rad)`}
function drawChart(){if(!data)return;let cv=$('#gammaChart'),ctx=cv.getContext('2d'),w=cv.width,h=cv.height,p={l:55,r:20,t:20,b:38},ys=[-1.6,0,1.6],y=g=>p.t+(1.6-g)/3.2*(h-p.t-p.b),x=i=>p.l+i/(data.events.length-1)*(w-p.l-p.r);ctx.clearRect(0,0,w,h);ctx.font='12px Arial';ctx.fillStyle='#62747c';ctx.strokeStyle='#b7c1bf';ctx.lineWidth=1;[-1,0,1].forEach(g=>{ctx.beginPath();ctx.moveTo(p.l,y(g));ctx.lineTo(w-p.r,y(g));ctx.stroke();ctx.fillText(`γ = ${g}`,8,y(g)+4)});ctx.beginPath();data.events.forEach((e,i)=>i?ctx.lineTo(x(i),y(e.gamma)):ctx.moveTo(x(i),y(e.gamma)));ctx.strokeStyle='#345e67';ctx.lineWidth=2;ctx.stroke();data.events.forEach((e,i)=>{ctx.beginPath();ctx.arc(x(i),y(e.gamma),i===index?7:4,0,Math.PI*2);ctx.fillStyle=COLORS[e.kind];ctx.fill();if(i===index){ctx.strokeStyle='#172832';ctx.lineWidth=2;ctx.stroke()}});ctx.fillStyle='#62747c';ctx.fillText(date(data.events[0]),p.l,h-12);let last=date(data.events.at(-1));ctx.fillText(last,w-p.r-ctx.measureText(last).width,h-12)}
$('#gammaChart').onclick=e=>{if(!data)return;let r=e.target.getBoundingClientRect(),px=(e.clientX-r.left)/r.width*e.target.width,i=Math.round((px-55)/(e.target.width-75)*(data.events.length-1));stop();index=Math.max(0,Math.min(data.events.length-1,i));render();location.hash='atlas'};
load(126);
